import { Router, type IRouter } from "express";
import healthRouter from "./health";
import clientsRouter from "./clients";
import tripsRouter from "./trips";
import accountsRouter from "./accounts";
import transactionsRouter from "./transactions";
import dashboardRouter from "./dashboard";
import aiRouter from "./ai";
import backupRouter from "./backup";
import restoreRouter from "./restore";
import settingsRouter from "./settings";
import accountRouter from "./account";
import supportRouter from "./support";
import consentRouter from "./consent";
import subscriptionRouter from "./subscription";
import exchangeRatesRouter from "./exchange-rates.js";
const router: IRouter = Router();

router.use(healthRouter);
router.use(settingsRouter);
router.use(clientsRouter);
router.use(tripsRouter);
router.use(accountsRouter);
router.use(transactionsRouter);
router.use(dashboardRouter);
router.use(aiRouter);
router.use(backupRouter);
router.use(restoreRouter);
router.use(exchangeRatesRouter);
router.use(accountRouter);
router.use(subscriptionRouter);
router.use(consentRouter);
router.use(supportRouter);

export default router;
