// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/finance-themes/GraphiteRose.tsx": () => import("../components/mockups/finance-themes/GraphiteRose.tsx"),
  "./components/mockups/finance-themes/MidnightPremium.tsx": () => import("../components/mockups/finance-themes/MidnightPremium.tsx"),
  "./components/mockups/finance-themes/OceanTeal.tsx": () => import("../components/mockups/finance-themes/OceanTeal.tsx")
};
