const colors = {
  light: {
    text: "#134e4a",
    tint: "#0f766e",
    background: "#f0faf9",
    foreground: "#134e4a",
    card: "#ffffff",
    cardForeground: "#134e4a",
    primary: "#0f766e",
    primaryForeground: "#ffffff",
    secondary: "#ccfbf1",
    secondaryForeground: "#134e4a",
    muted: "#e0f5f3",
    mutedForeground: "#5eada8",
    accent: "#ccfbf1",
    accentForeground: "#0f766e",
    destructive: "#ef4444",
    destructiveForeground: "#ffffff",
    success: "#16a34a",
    successForeground: "#ffffff",
    warning: "#f59e0b",
    warningForeground: "#ffffff",
    border: "#e0f5f3",
    input: "#e0f5f3",
    aed: "#0f766e",
    usd: "#16a34a",
    syp: "#7c3aed",
  },
  dark: {
    text: "#f8fafc",
    tint: "#f43f5e",
    background: "#0f0f14",
    foreground: "#f8fafc",
    card: "#16161f",
    cardForeground: "#e2e8f0",
    primary: "#f43f5e",
    primaryForeground: "#ffffff",
    secondary: "#1e1e2a",
    secondaryForeground: "#e2e8f0",
    muted: "#1e1e2a",
    mutedForeground: "#52525b",
    accent: "#1e1e2a",
    accentForeground: "#f43f5e",
    destructive: "#f43f5e",
    destructiveForeground: "#ffffff",
    success: "#22c55e",
    successForeground: "#ffffff",
    warning: "#f59e0b",
    warningForeground: "#ffffff",
    border: "#252530",
    input: "#1e1e2a",
    aed: "#f59e0b",
    usd: "#22c55e",
    syp: "#a78bfa",
  },
  radius: 12,
};

export default colors;
